steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['package', '-Dmaven.test.skip=true']
#  - name: maven:3-jdk-8
#    args: ['mkdir', '-p', 'target/dependency', '&&' ,'(cd target/dependency; jar -xf ../*.jar)']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/springbootdemo', '.' ]
images: ['gcr.io/${_PROJECT_ID}/springbootdemo']

substitutions:
  _PROJECT_ID: container-demo
