steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['package', '-Dmaven.test.skip=true']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_IMAGE_PATH}:$SHORT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_IMAGE_PATH}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: - "gcloud beta deploy releases create release-$SHORT_SHA"
    - "--project=${_PROJECT_ID}"
    - "--region=${_LOCATION}"
    - "--delivery-pipeline=${_PIPELINE_NAME}"
    - "--images=${_IMAGE}=${_IMAGE_PATH}:$SHORT_SHA"
images:
- '${_IMAGE_PATH}'
substitutions:
  _REPOSITORY:  # default value
  _IMAGE:  # default value
  _LOCATION:  # default value
  _PIPELINE_NAME:  # default value
  _IMAGE_PATH: -docker.pkg.dev/cloud-deploy-showcase//
